using Cuisinary.Data;
using Cuisinary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cuisinary.Services
{
    public class SqlRestaurantData : IRestaurantData
    {
        private CuisinaryDbContext _context;

        public SqlRestaurantData(CuisinaryDbContext context)
        {
            _context = context;
        }
        public Restaurant Add(Restaurant restaurant)
        {
            _context.Restaurants.Add(restaurant);
            //restaurant.Id = _context.Restaurants.Max(r => r.Id) + 1;
            //using ef the id will be autogenerated
            _context.SaveChanges();

            return restaurant;
        }

        public Restaurant Get(int id)
        {
            return _context.Restaurants.FirstOrDefault(r => r.Id == id);
        }

        public IEnumerable<Restaurant> GetAll()
        {
            return _context.Restaurants.OrderBy(r => r.Id); 
        }
    }
}
